import React from 'react';
import PropTypes from 'prop-types';
import localFont from 'next/font/local';
import './globals.css';
import '../index.scss';

// WRAPPERS
import LayoutWrapper from './common/components/wrappers/LayoutWrapper';
import Providers from './common/components/wrappers/Providers';

const gibson = localFont({
  src: [
    {
      path: '../assets/fonts/gibson-thin.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../assets/fonts/gibson-light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/gibson-regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/gibson-book.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/gibson-medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/gibson-semibold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/gibson-bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/gibson-heavy.otf',
      weight: '800',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-gibson'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gibson.className}>
        <Providers>
          <LayoutWrapper>{children}</LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node,
};
